version: '3'

tasks:
  run-small:
    cmds:
      - /usr/bin/time python3 obrc.py ../1brc/measurements_small.txt
  run:
    cmds:
      - /usr/bin/time python3 obrc.py ../1brc/measurements.txt

  test:
    cmds:
      - pytest
